version: '3.8'
services:
  rabbitmq_notification_streaming:
    image: rabbitmq:3-management
    container_name: service_rabbit_nestjs_notification_streaming
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_notification_streaming:/var/lib/rabbitmq
    networks:
      - nestjs_network_notification_streaming

  nestjs-app_notification_streaming:
    container_name: nestjs_app_notification_streaming
    build: .
    depends_on:
      - rabbitmq_notification_streaming
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    networks:
      - nestjs_network_notification_streaming

  postgresql_service_notification_streaming:
    image: postgres:15
    container_name: container_postgresql_service_notification_streaming
    ports:
      - ${WRITE_DB_PORT}:${WRITE_DB_PORT}
    networks:
      nestjs_network_notification_streaming:
    environment:
      POSTGRES_PASSWORD: ${WRITE_DB_PASSWORD}
      POSTGRES_USER: ${WRITE_DB_USERNAME}
      POSTGRES_DB: ${WRITE_DB_DATABASE}
    volumes:
      - type: volume
        source: write_pgsql_notification_streaming
        target: /var/lib/postgresql/data

volumes:
  rabbitmq_data_notification_streaming:
  write_pgsql_notification_streaming:

networks:
  nestjs_network_notification_streaming:
    driver: bridge
