version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: service_rabbit_nestjs
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - nestjs_network

  nestjs-app:
    container_name: nestjs_app_backend_sgp
    build: .
    depends_on:
      - rabbitmq
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nestjs_network

  postgresql_service:
    image: postgres:15
    container_name: container_postgresql_service
    ports:
      - ${WRITE_DB_PORT}:${WRITE_DB_PORT}
    networks:
      nestjs_network:
    environment:
      POSTGRES_PASSWORD: ${WRITE_DB_PASSWORD}
      POSTGRES_USER: ${WRITE_DB_USERNAME}
      POSTGRES_DB: ${WRITE_DB_DATABASE}
    volumes:
      - type: volume
        source: write_pgsql
        target: /var/lib/postgresql/data

volumes:
  rabbitmq_data:
  write_pgsql:

networks:
  nestjs_network:
    driver: bridge
